/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cryptodroid_crypto_AES */

#ifndef _Included_com_cryptodroid_crypto_AES
#define _Included_com_cryptodroid_crypto_AES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cryptodroid_crypto_AES
 * Method:    GenerateIV
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cryptodroid_crypto_AES_GenerateIV
  (JNIEnv *, jclass);

/*
 * Class:     com_cryptodroid_crypto_AES
 * Method:    GenerateKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cryptodroid_crypto_AES_GenerateKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
