/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cryptodroid_crypto_AES_CBC */

#ifndef _Included_com_cryptodroid_crypto_AES_CBC
#define _Included_com_cryptodroid_crypto_AES_CBC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cryptodroid_crypto_AES_CBC
 * Method:    Encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cryptodroid_crypto_AES_00024CBC_Encrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_cryptodroid_crypto_AES_CBC
 * Method:    Decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cryptodroid_crypto_AES_00024CBC_Decrypt
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
